In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
print(arr)

[1 2 3 4 5 6]


In [4]:
print(np.__version__)

1.20.1


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


0D array 

In [6]:
odarr = np.array(20)

In [7]:
print (odarr)
print (odarr.ndim)

20
0


1D array

In [8]:
one_D_array = np.array([1,2,3,4,5,6])

In [9]:
print(one_D_array)
print (one_D_array.ndim)

[1 2 3 4 5 6]
1


2D array 

In [17]:
two_D_array = np.array([[1,2,3],
                        [4,5,6]])

In [18]:
print (two_D_array)
print (two_D_array.ndim)

[[1 2 3]
 [4 5 6]]
2


3D array 

In [23]:
three_D_array = np.array([[[1,2,3],
                           [4,5,6]],
                          [[7,8,9],
                           [10,11,12]]])

In [24]:
print (three_D_array)
print (three_D_array.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


indexing 

In [25]:
print (one_D_array[3])

4


In [26]:
print(two_D_array[1,2])

6


In [27]:
print(three_D_array[0,1,1])

5


negative indexing

In [28]:
print (one_D_array[-1])

6


In [29]:
print (two_D_array[-1,-1])

6


In [30]:
print(three_D_array[-1,-1,-2])

11
